### ISSUE TITLE
Revised Code for Map and Widget

### ISSUE THREAD

**Issue by LCLambert** [denverpost/cannabist#10]
Hell Guys,

Below is the revised code for the map and widget. I have put these in one ticket because the new code for the widget and map support one another The new widget supports the registration link and also allows for the user to filter between dispensary type before entering the map.

Best Buds Widget Code
```
<a href="http://www.thecannabist.co/map/"><img src="http://bestbudsapp.com/sites/default/files/cannabist_map_new.jpg"></a>
<form action="http://www.thecannabist.co/map/" type="post" style="margin-top:15px;font-family: Arial;font-size:13px;">
	<div class="dispensary selector" style="margin-bottom:10px;">
		<label><strong>Dispensary Type</strong></label>
		<label><input type="radio" name="field_dispensary_type_value" value="all">Both</label>
		<lable><input type="radio" name="field_dispensary_type_value" value="1">Recreational</lable>
		<label><input type="radio" name="field_dispensary_type_value" value="2">Medicinal</label>
	</div>
	<input id="origin" placeholder="City, State or Zip" style="padding:5px;width:40%;" type="text" name="field_geofield_distance[origin]">
	<input id="title" placeholder="Strain or Product Name" style="padding:5px;width:40%;" name="title" type="text">
	<button type="submit" style="display: inline-block; border: 0px none; background: none repeat scroll 0px 0px rgb(92, 184, 92); color: rgb(255, 255, 255); font-size: 12px; padding: 6px 12px;">Submit</button>
</form>
<p style="font-family: Arial;font-size:13px;color:#888;">Not listed on the map? <a href="http://bestbudsapp.com/dispensary/register">Click here</a> to register your store.</p>
```
Best Buds Map Code
```
<script>
jQuery(document).ready(function($){function getUrlParameter(sParam)
{var sPageURL=window.location.search.substring(1);var sURLVariables=sPageURL.split('&');for(var i=0;i<sURLVariables.length;i++)
{var sParameterName=sURLVariables[i].split('=');if(sParameterName[0]==sParam)
{return sParameterName[1];}}}
var type=getUrlParameter('field_dispensary_type_value');origin=getUrlParameter('field_geofield_distance%5Borigin%5D');var title=getUrlParameter('title');if(origin){$('#mapframe').attr('src','http://bestbudsapp.com/?field_dispensary_type_value='+type+'&field_dispensary_type_value_1='+type+'&field_geofield_distance[origin]='+origin+'&mode=embed');}
if(title){$('iframe').attr('src','http://bestbudsapp.com/?field_dispensary_type_value='+type+'&field_dispensary_type_value_1='+type+'&title='+title+'&title_1='+title+'&mode=embed');}
if(title&&origin){$('iframe').attr('src','http://bestbudsapp.com/?field_dispensary_type_value='+type+'&field_dispensary_type_value_1='+type+'&field_geofield_distance[origin]='+origin+'&title='+title+'&title_1='+title+'&mode=embed');}});
</script>

<iframe id="mapframe" src="http://bestbudsapp.com/?mode=embed" width="100%" frameborder="0" height="100%"></iframe>
```

Thanks, Lance

**Comment by freejoe76** [comment]
Hi Lance, I'm back Tuesday. Maybe @schneidan can pick this up in the meantime, I don't know.

**Comment by schneidan** [comment]
Joe, if you tell me this is as easy as pasting it in and it will be obvious where, I will do it, but if it can wait until Tuesday I'd be more comfortable letting you do it and keeping my focus on Reverb...

**Comment by LCLambert** [comment]
I believe it's just a swap out of code, so should be easy. If not just let
me know so I can notify the vendor. I actually had a question about Reverb
Dan, I'll cruise up in a few.

Lance C. Lambert
Director of Digital Products & Platforms
Digital First Media | The Denver Post

LCLambert@DenverPost.com
o: 303.954.1711 | c: 805.746.1921

**Comment by freejoe76** [comment]
Hi Lance,

The Best Buds changes are online at http://www-beta.thecannabist.co/ . If those are acceptable I'll promote to production. 

-Joe

**Comment by LCLambert** [comment]
That's perfect, thanks!

On Tuesday, January 20, 2015, Joe Murphy <notifications@github.com> wrote:

> Hi Lance,
>
> The Best Buds changes are online at http://www-beta.thecannabist.co/ . If
> those are acceptable I'll promote to production.
>
> -Joe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/cannabist/issues/10#issuecomment-70688387>.
>


-- 
Lance C. Lambert
Director of Digital Products & Platforms
Digital First Media | The Denver Post

LcLambert@DenverPost.com
o: 303.954.1711 | c: 805.746.1921

.:iPhone mail:.

**Comment by freejoe76** [comment]
Okay, I just pushed this live. http://thecannabist.co/

**Comment by schneidan** [comment]
merged into master?



Daniel J. Schneider
Photographer and Journalist
Denver, Colorado
Scrollwright.com
twitter.com/schneidan <http://www.twitter.com/schneidan>
P: 720-732-1763

**Comment by freejoe76** [comment]
Yes.

**Comment by LCLambert** [comment]
Thanks agajn!

On Tuesday, January 20, 2015, Joe Murphy <notifications@github.com> wrote:

> Yes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/cannabist/issues/10#issuecomment-70757209>.
>


-- 
Lance C. Lambert
Director of Digital Products & Platforms
Digital First Media | The Denver Post

LcLambert@DenverPost.com
o: 303.954.1711 | c: 805.746.1921

.:iPhone mail:.
