### ISSUE TITLE
Allow different image sizes for article-embedded images

### ISSUE THREAD

**Issue by AletaLabak** [denverpost/cannabist#11]
When adding an embedded image in WP, would be awesome if there was a way to select various sizes -- small for mugshots, medium for stories with many embedded images.

A couple of examples where adjustable photo sizing might help:
A big mugshot in this one:
http://www.thecannabist.co/2015/01/28/furniture-store-marijuana-grow/28722/
Gift guide with many images:
http://www.thecannabist.co/2014/12/04/cannabists-2014-gift-guide-part-2-superfly-stoner-weed-gifts/24479/ 

Thanks for investigating!

**Comment by schneidan** [comment]
This is done and Aleta has the skinny.
