### ISSUE TITLE
Seeking site-level changes to Cannabist map

### ISSUE THREAD

**Issue by AletaLabak** [denverpost/cannabist#13]
SIDEBAR WIDGET

We need the homepage cleaned up ASAP. We want only the map, the 'Powered by BB' logo and the 'Not listed on the map' link. We don't think the search functionality has a purpose on the homepage. And getting rid of it will allow us to tighten up the rail - and give better play to the ads and content below it. If it's set up this way because you can't do any mobile searches on the main map page, oy. Making mobile users go back to the widget if they want to do a new search doesn't seem to be good UX.

![image](https://cloud.githubusercontent.com/assets/10840010/6081506/3e7cb4a2-add7-11e4-91e5-82024ff82a91.png)

Inline image 2

MAIN MAP PAGE

1. Having no search option on the mobile map page is not ideal for usability. Could a search bar be anchored at the top next to the "Powered by BB" logo, and both be put on an opaque background? As you'll see in the image below, it looks messy with that logo on top of the map. This would also be a good place to add the "Not listed on the map? Click here to register your store" message on mobile.

![image](https://cloud.githubusercontent.com/assets/10840010/6081522/5fe43a02-add7-11e4-96a5-82939c459f70.png)

Inline image 1

2. We need that message "Not listed on the map? Click here to register your store" on the main map. What if it were up top, next to the  "Powered by BB logo"?  The city search tab does not need to be that wide:

![image](https://cloud.githubusercontent.com/assets/10840010/6081532/7a22e92c-add7-11e4-8fc9-b3938f4633fc.png)

Inline image 6

3. The initial map load time on PC is working great for Aleta and I on desktop, and it was OK on mobile too. 

4. The city search functionality takes a long time to work -- about 11 seconds.

5. Not sure about their note about the 50-mile radius. When we pull it up, on desktop or mobile, and we zoom out, all of the shops show up - which is ideal. We want it that way and hope that won't change.

6. Again, we'd like any mention of the word 'medicinal' changed to 'medical.'

7. They still need to go through the state's registry and add a lot more shops. The Sedgwick shop in NE Colorado isn't on there, and they're missing most of the Aurora shops. I searched for Euflora, just to see if their downtown Denver shop or their Aurora location popped up, and neither did. That revealed another problem: Euflora's Denver location is on BB's map, but the store is still titled under the shop's "Doing Business As" name, JS Investments, at 401 16th St. We *always* need the actual shop name on this map. Users have no idea what JS Investments is, but they do know what Euflora is, and they'll be searching for Euflora. It is great to see that many of the DBA names on the unclaimed listings have been fixed, though.

8. Does BB have plans to expand into Washington, Cali, Oregon and beyond? We hope so! We'd love for this map to eventually stretch beyond Colorado's borders!

9. Some odd behavior on Android, the zoom and "Powered by BB" disappear at times when in landscape view, as does the legend: 

![image](https://cloud.githubusercontent.com/assets/10840010/6081544/95b2a74a-add7-11e4-8ccd-6cc803044dab.png)

Inline image 3

**Comment by freejoe76** [comment]
Thanks Aleta. I can fix your homepage request, which I did, so I'm closing this issue.

**Comment by AletaLabak** [comment]
Thank you for the fix!
