### ISSUE TITLE
Native Advertising - Serving Tags Aren't Working

### ISSUE THREAD

**Issue by jdflanagan** [denverpost/cannabist#15]
Hi there - 
Please see the below preview URL and notice that the right rail serving tags aren't working.

http://www.thecannabist.co/sponsor-content/?prx_t=-aoBAK0wCA4VkLA&prx_ro=s

We should see a 300x250 ad unit, a facebook feed and a twitter feed being pulled into the right rail via the following serving tags:
*ad_right
*facebook_feed
*twitter_feed

This same article preview can be seen working correctly on denverpost.com at the below URL:

http://www.denverpost.com/sponsor-content?prx_t=-aoBAAAAAA6CELA&prx_ro=s

Ed, can you please work with Dan and Joe to get this corrected and make sure that the serving tags are working properly?

Thank you!
Jen

**Comment by jdflanagan** [comment]
@brianedsauer @schneidan @freejoe76

**Comment by brianedsauer** [comment]
Yep, I'll help get this rolling.

On Tuesday, February 17, 2015, jdflanagan <notifications@github.com> wrote:

> @brianedsauer <https://github.com/brianedsauer> @schneidan
> <https://github.com/schneidan> @freejoe76 <https://github.com/freejoe76>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/cannabist/issues/15#issuecomment-74695198>.
>


-- 


Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by schneidan** [comment]
Is this a problem with Nativo? I see the divs on the page, but they have no content in there. I don't see any JS errors. If this isn't actually a Cannabist problem, I'd like to close this issue.

**Comment by jdflanagan** [comment]
This isn't a Nativo issue, since it is working on DenverPost.com. Please
keep the issue open. Ed can help to troubleshoot.

  [image: AdTaxi Networks]
<http://www.adtaxinetworks.com/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Jennifer
Flanagan  |  Sr. Dir, Marketing Solutions
------------------------------
   303.954.2476
<303.954.2476?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  |   612.201.6552
<612.201.6552?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 jflanagan@adtaxinetworks.com
  @  jdflanagan
<https://twitter.com/jdflanagan?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  [image:
Twitter]
<https://twitter.com/AdTaxi?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
LinkedIn]
<https://www.linkedin.com/company/2816124?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
Google PSP Premier Site Member]
<http://www.google.com/intl/en/ads/premiersmbpartner/advertisers-findpartner.html#tab=partner-adtaxinetworks-com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by jdflanagan** [comment]
I also noticed that there is a 468x60 ad at the top of the article page. We either need to have this removed or change it also to a serving tag (ad_top) so that we can have the sponsoring advertiser's ad appear in this slot.

**Comment by schneidan** [comment]
Are you talking about the 728x90 leaderboard? I can remove it from the page on this template only. If you want to inject something in its place that's up to you. That is, however, a separate issue and was not part of your original request.

**Comment by jdflanagan** [comment]
The ad size I'm seeing is a 468x60. If it can accommodate a 728x90, that's
great. In order for us to inject a sponsor's ad there, we need to utilize
the serving tags - which is the same issue as the right rail placements.

  [image: AdTaxi Networks]
<http://www.adtaxinetworks.com/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Jennifer
Flanagan  |  Sr. Dir, Marketing Solutions
------------------------------
   303.954.2476
<303.954.2476?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  |   612.201.6552
<612.201.6552?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 jflanagan@adtaxinetworks.com
  @  jdflanagan
<https://twitter.com/jdflanagan?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  [image:
Twitter]
<https://twitter.com/AdTaxi?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
LinkedIn]
<https://www.linkedin.com/company/2816124?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
Google PSP Premier Site Member]
<http://www.google.com/intl/en/ads/premiersmbpartner/advertisers-findpartner.html#tab=partner-adtaxinetworks-com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by brianedsauer** [comment]
Is there currently any campaign page on Cannabist where the right rail
content is serving correctly?


Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by jdflanagan** [comment]
We don't have any live campaign on The Cannabist. This is a test preview.
Here's another version:

Cannabist:
http://www.thecannabist.co/sponsor-content/?prx_t=CK0BAAAAAA4VkLA&prx_ro=s

DailyNews:
http://www.dailynews.com/sponsor-content?prx_t=CK0BAAAAAAFVQLA&prx_ro=s

  [image: AdTaxi Networks]
<http://www.adtaxinetworks.com/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Jennifer
Flanagan  |  Sr. Dir, Marketing Solutions
------------------------------
   303.954.2476
<303.954.2476?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  |   612.201.6552
<612.201.6552?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 jflanagan@adtaxinetworks.com
  @  jdflanagan
<https://twitter.com/jdflanagan?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  [image:
Twitter]
<https://twitter.com/AdTaxi?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
LinkedIn]
<https://www.linkedin.com/company/2816124?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
Google PSP Premier Site Member]
<http://www.google.com/intl/en/ads/premiersmbpartner/advertisers-findpartner.html#tab=partner-adtaxinetworks-com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by brianedsauer** [comment]
I believe we just need to add the following JS file to the Cannabist
template:

http://local.denverpost.com/common/dfm/assets/js/nativo/nativo-scriptwell-ngps.js





Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by schneidan** [comment]
I have added that script to the sponsored content page template, and removed the ad. The ad container div is still there if you want to inject something into it. It is designed for a 728x90 leaderboard; there are no 468x60 ad calls in the Cannabist theme that I can find. You will need to test the screen size and only inject an ad when there is room for it.

**Comment by jdflanagan** [comment]
Thanks for removing the ad.

I'm still not seeing the right rail ad or feeds come through the serving
tags:

http://www.thecannabist.co/sponsor-content/?prx_t=zaYBAAAAAA4VkLA&prx_ro=s

Anything else we can try, Ed?

  [image: AdTaxi Networks]
<http://www.adtaxinetworks.com/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Jennifer
Flanagan  |  Sr. Dir, Marketing Solutions
------------------------------
   303.954.2476
<303.954.2476?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  |   612.201.6552
<612.201.6552?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 jflanagan@adtaxinetworks.com
  @  jdflanagan
<https://twitter.com/jdflanagan?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  [image:
Twitter]
<https://twitter.com/AdTaxi?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
LinkedIn]
<https://www.linkedin.com/company/2816124?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
Google PSP Premier Site Member]
<http://www.google.com/intl/en/ads/premiersmbpartner/advertisers-findpartner.html#tab=partner-adtaxinetworks-com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by brianedsauer** [comment]
Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by brianedsauer** [comment]
Great, thank you for adding that script.

Yep, I see what is happening.

Dan, can you please change the URL of that JS script to the following:

http://local.denverpost.com/common/dfm/assets/js/nativo/nativo-scriptwell-cannabist.js

Thanks!



Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by schneidan** [comment]
Done. I see the rail contents now. Can you guys center the things that don't use the full width to match Cannabist style, please? Thanks.

Closing this issue now.

**Comment by brianedsauer** [comment]
On Tue, Feb 17, 2015 at 4:30 PM, Daniel J. Schneider <
notifications@github.com> wrote:

> Can you guys center the things that don't use the full width to match
> Cannabist style, please?


Yes, I will correct the display to match the Cannabist style.

Thanks for updating that file URL.


Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by schneidan** [comment]
No problem. Thanks, Ed.



Daniel J. Schneider
Photographer and Journalist
Denver, Colorado
Scrollwright.com
twitter.com/schneidan <http://www.twitter.com/schneidan>
P: 720-732-1763
