### ISSUE TITLE
The Cannabist - Native Advertising Integration

### ISSUE THREAD

**Issue by jdflanagan** [denverpost/cannabist#9]
We are in the process of rolling out a new native advertising platform across all of the DFM properties. In addition to this, we'd like to get it set up on TheCannabist.co. We recently sold a large content program that is to run on TheCannabist, so there is a bit of urgency around getting the integration in place. I have communicated with Kevin Dale & Ricardo Baca and received their approval to move forward. In order to support this, we will need two template pages created within the site:
Article Template - go-live date: 1/26/15
Custom Channel Template - go-live date: 2/16/15
Below is a link to instructions for the creation of the article template page:

https://docs.google.com/a/adtaxinetworks.com/document/d/1NksYks_FQaER0J2jHhNHLMzX_2zMuzEmLpYUoLANDUQ/edit

This will be re-used across all advertisers, so this will only need to be created once. After the article template is created, we will need to create the template for the channel. Specific details on that to come later. 

If you have any questions about the implementation, Ed Sauer (cc'd on the thread) should be your primary point of contact.

**Comment by freejoe76** [comment]
including @brianedsauer on this thread.

**Comment by brianedsauer** [comment]
sweet. i can hear you :)

**Comment by jdflanagan** [comment]
Checking in on the progress of the Nativo integration. Can you please let me know what the ETA is on finalizing the article template and getting the code on TheCannabist.co?

**Comment by schneidan** [comment]
I'm working on this today, folks. I have a question, though, that I hope one of you can answer:

The instructions seem slightly obtuse, but just to clarify: You want a 100% blank page -- nothing in the headline (except except the `@Title` comment), nothing in the body (except the `@Content` comment) and nothing in the sidebar (except the Sponsored Content explanation widget). Does that sound right?

**Comment by brianedsauer** [comment]
Dan and I are discussing this on Skype, just FYI to everyone else....

Thanks,
Ed



Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by schneidan** [comment]
Changes made and posted to beta here: http://www-beta.thecannabist.co/sponsor-content/

Please let me know if this is correct and I will promote to prod.

**Comment by brianedsauer** [comment]
Dan,

This looks good to me.
The Nativo JS script is present, the 'What Is Sponsored...' text block is
present, and the Nativo serving tags are all present, too (adsquare,
fb-likebox, tw-feedbox).

Jen — please take a look and let us know.

Thanks,
Ed



Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by jdflanagan** [comment]
Thanks guys. All looks good to me as well.

Ed - can you confirm if we should send this URL to Nativo, so we can set up
preview links to test, and then we will push to the live environment and
update the URL (SAXO-like process) - or if we want to push this to the live
environment right now and send the Nativo to test (NGPS-like process)?

  [image: AdTaxi Networks]
<http://www.adtaxinetworks.com/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 Jennifer
Flanagan  |  Sr. Dir, Marketing Solutions
------------------------------
   303.954.2476
<303.954.2476?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  |   612.201.6552
<612.201.6552?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 jflanagan@adtaxinetworks.com
  @  jdflanagan
<https://twitter.com/jdflanagan?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
  [image:
Twitter]
<https://twitter.com/adtaxinetworks?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
LinkedIn]
<https://www.linkedin.com/company/2816124?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
 [image:
Google PSP Premier Site Member]
<http://www.google.com/intl/en/ads/premiersmbpartner/advertisers-findpartner.html#tab=partner-adtaxinetworks-com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by brianedsauer** [comment]
I think we should go with the NGPS-like process. Good idea.




Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677

**Comment by jdflanagan** [comment]
Okay. Let me know once this has been pushed to live environment and what
the URL is.

**Comment by schneidan** [comment]
This is live at: http://www.thecannabist.co/sponsor-content/

Closing this ticket; please open a new one if you have further requests.

**Comment by brianedsauer** [comment]
Great, Dan, thank you for pushing this live!

Ed


On Wednesday, January 21, 2015, Daniel J. Schneider <
notifications@github.com> wrote:

> This is live at: http://www.thecannabist.co/sponsor-content/
>
> Closing this ticket; please open a new one if you have further requests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/denverpost/cannabist/issues/9#issuecomment-70933525>.
>


-- 


Ed Sauer

Senior UI Web Developer

Digital First Media


esauer@medianewsgroup.com

skype  brianedsauer

mobile 303-520-3677
